# Base configs
base_url: "dwood.pics"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
header:dwood.pics
 title: "A Big Hand For Germany"
social_urls:
  instagram: "https://www.instagram.com/analoguetigers"
 
